### ISSUE TITLE
Docs Link Broken

### ISSUE THREAD

**Issue by cawoodm** [OttoRobba/ox#49]
I know this is abandoned but do you have the docs available anywhere?

The link from the readme is broken:
http://ox2d.com/docs

**Comment by ThaisRobba** [comment]
I removed the CNAME file, it should propagate soon. http://ottorobba.github.io/ox/docs/

You can also see it in the gh-pages branch.

**Comment by cawoodm** [comment]
http://ottorobba.github.io/ox/ links "Docs" to http://ottorobba.github.io/docs/ which is broken.

**Comment by ThaisRobba** [comment]
Fixed.
